In [1]:
doc = 'The faster Harry got to the store, the faster Harry, the fater, would get home'

In [2]:
from nltk.tokenize import word_tokenize

In [3]:
tokens = word_tokenize(doc)
stop_punc = [',',';','.']
final_tokens = [x for x in tokens if x not in stop_punc]
final_tokens

['The',
 'faster',
 'Harry',
 'got',
 'to',
 'the',
 'store',
 'the',
 'faster',
 'Harry',
 'the',
 'fater',
 'would',
 'get',
 'home']

In [5]:
from collections import Counter
bag_of_words = Counter(final_tokens)
bag_of_words.most_common(3)

[('the', 3), ('faster', 2), ('Harry', 2)]

In [8]:
docs = ['The faster Harry got to the store, the faster and faster Harry would get home.', 'Harry is hairy and faster than Jill.','Jill is not as hairy as Harry.']

In [7]:
from nltk.tokenize import word_tokenize

In [10]:
stop_punc = [',',';','.']
docs_tokens = []
for doc in docs:
    tokens = word_tokenize(doc)
    final_tokens = [x for x in tokens if x not in stop_punc]
    docs_tokens += [final_tokens]
    
print(docs_tokens)

[['The', 'faster', 'Harry', 'got', 'to', 'the', 'store', 'the', 'faster', 'and', 'faster', 'Harry', 'would', 'get', 'home'], ['Harry', 'is', 'hairy', 'and', 'faster', 'than', 'Jill'], ['Jill', 'is', 'not', 'as', 'hairy', 'as', 'Harry']]


In [11]:
all_docs_tokens = []
for each_doc_tokens in docs_tokens:
    all_docs_tokens.extend(each_doc_tokens)
    
all_docs_tokens

['The',
 'faster',
 'Harry',
 'got',
 'to',
 'the',
 'store',
 'the',
 'faster',
 'and',
 'faster',
 'Harry',
 'would',
 'get',
 'home',
 'Harry',
 'is',
 'hairy',
 'and',
 'faster',
 'than',
 'Jill',
 'Jill',
 'is',
 'not',
 'as',
 'hairy',
 'as',
 'Harry']

In [12]:
vocab = sorted(set(all_docs_tokens))
print(vocab)

['Harry', 'Jill', 'The', 'and', 'as', 'faster', 'get', 'got', 'hairy', 'home', 'is', 'not', 'store', 'than', 'the', 'to', 'would']


In [13]:
import numpy as np
from collections import Counter

vocab_size = len(vocab)
num_docs = len(docs)
TF_vectors = np.zeros((num_docs, vocab_size), float)
print(TF_vectors)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
for i, token_list in enumerate(docs_tokens):
    doc_len = len(token_list)
    print(doc_len)
    token_counts = Counter(token_list)
    print(token_counts)
    for key, value in token_counts.items():
        TF_vectors[i][vocab.index(key)] = value / doc_len

15
Counter({'faster': 3, 'Harry': 2, 'the': 2, 'The': 1, 'got': 1, 'to': 1, 'store': 1, 'and': 1, 'would': 1, 'get': 1, 'home': 1})
7
Counter({'Harry': 1, 'is': 1, 'hairy': 1, 'and': 1, 'faster': 1, 'than': 1, 'Jill': 1})
7
Counter({'as': 2, 'Jill': 1, 'is': 1, 'not': 1, 'hairy': 1, 'Harry': 1})


In [15]:
print(TF_vectors.round(3))

[[0.133 0.    0.067 0.067 0.    0.2   0.067 0.067 0.    0.067 0.    0.
  0.067 0.    0.133 0.067 0.067]
 [0.143 0.143 0.    0.143 0.    0.143 0.    0.    0.143 0.    0.143 0.
  0.    0.143 0.    0.    0.   ]
 [0.143 0.143 0.    0.    0.286 0.    0.    0.    0.143 0.    0.143 0.143
  0.    0.    0.    0.    0.   ]]


In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
TF_vectorizer = CountVectorizer()
TF_vectors = TF_vectorizer.fit_transform(docs)

In [21]:
TF_vectorizer.get_feature_names()

['and',
 'as',
 'faster',
 'get',
 'got',
 'hairy',
 'harry',
 'home',
 'is',
 'jill',
 'not',
 'store',
 'than',
 'the',
 'to',
 'would']

In [22]:
print(TF_vectors.toarray())

[[1 0 3 1 1 0 2 1 0 0 0 1 0 3 1 1]
 [1 0 1 0 0 1 1 0 1 1 0 0 1 0 0 0]
 [0 2 0 0 0 1 1 0 1 1 1 0 0 0 0 0]]


In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
TFIDF_vectorizer = TfidfVectorizer()
TFIDF_vectors = TFIDF_vectorizer.fit_transform(docs)
print(TFIDF_vectors.toarray())

[[0.1614879  0.         0.48446369 0.21233718 0.21233718 0.
  0.25081952 0.21233718 0.         0.         0.         0.21233718
  0.         0.63701154 0.21233718 0.21233718]
 [0.36930805 0.         0.36930805 0.         0.         0.36930805
  0.28680065 0.         0.36930805 0.36930805 0.         0.
  0.48559571 0.         0.         0.        ]
 [0.         0.75143242 0.         0.         0.         0.28574186
  0.22190405 0.         0.28574186 0.28574186 0.37571621 0.
  0.         0.         0.         0.        ]]


In [30]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(TF_vectors, TF_vectors)

array([[1.        , 0.42111744, 0.12379689],
       [0.42111744, 1.        , 0.50395263],
       [0.12379689, 0.50395263, 1.        ]])

In [29]:
cosine_similarity(TFIDF_vectors, TFIDF_vectors)

array([[1.        , 0.31049032, 0.05565787],
       [0.31049032, 1.        , 0.38022254],
       [0.05565787, 0.38022254, 1.        ]])

In [31]:
cosine_similarity(TFIDF_vectors[0], TFIDF_vectors[2]).flatten()[0]

0.055657865713652735